name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sriramdock/yoctobuilder:v1.9
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    env:
      # optional: expose tokens if needed inside steps
      DOWNLOADS_UPLOAD_TOKEN: ${{ secrets.DOWNLOADS_UPLOAD_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Make build script executable
        run: chmod +x $GITHUB_WORKSPACE/scripts/build.sh
      - name: Run build
        run: $GITHUB_WORKSPACE/scripts/build.sh --kasfile=kas-prod --priv-key=${PRIV_KEY_SIGNING} --repo-slug=${{ github.repository }} --build-number=${{ github.run_number }}
        env:
          PRIV_KEY_SIGNING: ${{ secrets.PRIV_KEY_SIGNING }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/sm*
